//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErcotAPITest.ErcotNodalService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class FaultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReplyType replyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReplyType Reply {
            get {
                return this.replyField;
            }
            set {
                this.replyField = value;
                this.RaisePropertyChanged("Reply");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class ReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string replyCodeField;
        
        private string[] errorField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string[] idField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReplyCode {
            get {
                return this.replyCodeField;
            }
            set {
                this.replyCodeField = value;
                this.RaisePropertyChanged("ReplyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Order=1)]
        public string[] Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("TimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID", Order=3)]
        public string[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class PayloadType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Compressed", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Document", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        Compressed,
        
        /// <remarks/>
        Document,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestTypeMarketType marketTypeField;
        
        private bool marketTypeFieldSpecified;
        
        private System.DateTime operatingDateField;
        
        private bool operatingDateFieldSpecified;
        
        private System.DateTime tradingDateField;
        
        private bool tradingDateFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private System.DateTime endTimeField;
        
        private bool endTimeFieldSpecified;
        
        private string zoneField;
        
        private string aSTypeField;
        
        private string optionField;
        
        private string sortByField;
        
        private string[] idField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestTypeMarketType MarketType {
            get {
                return this.marketTypeField;
            }
            set {
                this.marketTypeField = value;
                this.RaisePropertyChanged("MarketType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarketTypeSpecified {
            get {
                return this.marketTypeFieldSpecified;
            }
            set {
                this.marketTypeFieldSpecified = value;
                this.RaisePropertyChanged("MarketTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime OperatingDate {
            get {
                return this.operatingDateField;
            }
            set {
                this.operatingDateField = value;
                this.RaisePropertyChanged("OperatingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatingDateSpecified {
            get {
                return this.operatingDateFieldSpecified;
            }
            set {
                this.operatingDateFieldSpecified = value;
                this.RaisePropertyChanged("OperatingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime TradingDate {
            get {
                return this.tradingDateField;
            }
            set {
                this.tradingDateField = value;
                this.RaisePropertyChanged("TradingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TradingDateSpecified {
            get {
                return this.tradingDateFieldSpecified;
            }
            set {
                this.tradingDateFieldSpecified = value;
                this.RaisePropertyChanged("TradingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
                this.RaisePropertyChanged("StartTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeSpecified {
            get {
                return this.endTimeFieldSpecified;
            }
            set {
                this.endTimeFieldSpecified = value;
                this.RaisePropertyChanged("EndTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
                this.RaisePropertyChanged("Zone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ASType {
            get {
                return this.aSTypeField;
            }
            set {
                this.aSTypeField = value;
                this.RaisePropertyChanged("ASType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("Option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
                this.RaisePropertyChanged("SortBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ID", Order=9)]
        public string[] ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=10)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public enum RequestTypeMarketType {
        
        /// <remarks/>
        DAM,
        
        /// <remarks/>
        RTM,
        
        /// <remarks/>
        SASM,
        
        /// <remarks/>
        HRUC,
        
        /// <remarks/>
        DRUC,
        
        /// <remarks/>
        SCED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1." +
        "0.xsd")]
    public partial class AttributedDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EncodedString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PasswordString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
        ".xsd")]
    public partial class AttributedString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1." +
            "0.xsd", DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
        ".xsd")]
    public partial class EncodedString : AttributedString {
        
        private string encodingTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string EncodingType {
            get {
                return this.encodingTypeField;
            }
            set {
                this.encodingTypeField = value;
                this.RaisePropertyChanged("EncodingType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
        ".xsd")]
    public partial class KeyIdentifierType : EncodedString {
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
        ".xsd")]
    public partial class BinarySecurityTokenType : EncodedString {
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0" +
        ".xsd")]
    public partial class PasswordString : AttributedString {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class ReplayDetectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EncodedString nonceField;
        
        private AttributedDateTime createdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EncodedString Nonce {
            get {
                return this.nonceField;
            }
            set {
                this.nonceField = value;
                this.RaisePropertyChanged("Nonce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AttributedDateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class HeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderTypeVerb verbField;
        
        private string nounField;
        
        private ReplayDetectionType replayDetectionField;
        
        private string revisionField;
        
        private string sourceField;
        
        private string userIDField;
        
        private string messageIDField;
        
        private string commentField;
        
        private System.Xml.XmlElement[] anyField;
        
        public HeaderType() {
            this.verbField = HeaderTypeVerb.get;
            this.revisionField = "001";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderTypeVerb Verb {
            get {
                return this.verbField;
            }
            set {
                this.verbField = value;
                this.RaisePropertyChanged("Verb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Noun {
            get {
                return this.nounField;
            }
            set {
                this.nounField = value;
                this.RaisePropertyChanged("Noun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReplayDetectionType ReplayDetection {
            get {
                return this.replayDetectionField;
            }
            set {
                this.replayDetectionField = value;
                this.RaisePropertyChanged("ReplayDetection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=8)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public enum HeaderTypeVerb {
        
        /// <remarks/>
        cancel,
        
        /// <remarks/>
        canceled,
        
        /// <remarks/>
        change,
        
        /// <remarks/>
        changed,
        
        /// <remarks/>
        create,
        
        /// <remarks/>
        created,
        
        /// <remarks/>
        close,
        
        /// <remarks/>
        closed,
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        deleted,
        
        /// <remarks/>
        get,
        
        /// <remarks/>
        reply,
        
        /// <remarks/>
        submit,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        updated,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ercot.com/wsdl/2007-06/nodal/ewsConcrete", ConfigurationName="ErcotNodalService.Operations")]
    public interface Operations {
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketTransactions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ErcotAPITest.ErcotNodalService.FaultMessage), Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketTransactions", Name="FaultMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        ErcotAPITest.ErcotNodalService.MarketTransactionsResponse MarketTransactions(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> MarketTransactionsAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/Alerts", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ErcotAPITest.ErcotNodalService.FaultMessage), Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/Alerts", Name="FaultMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        ErcotAPITest.ErcotNodalService.MarketTransactionsResponse Alerts(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/Alerts", ReplyAction="*")]
        System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> AlertsAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ErcotAPITest.ErcotNodalService.FaultMessage), Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketInfo", Name="FaultMessage", Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        ErcotAPITest.ErcotNodalService.MarketTransactionsResponse MarketInfo(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/BusinessService/NodalService.serviceagent/HttpEndPoint/MarketInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> MarketInfoAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class RequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderType headerField;
        
        private RequestType requestField;
        
        private PayloadType payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PayloadType Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message")]
    public partial class ResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderType headerField;
        
        private ReplyType replyField;
        
        private PayloadType payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderType Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReplyType Reply {
            get {
                return this.replyField;
            }
            set {
                this.replyField = value;
                this.RaisePropertyChanged("Reply");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PayloadType Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarketTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message", Order=0)]
        public ErcotAPITest.ErcotNodalService.RequestMessage RequestMessage;
        
        public MarketTransactionsRequest() {
        }
        
        public MarketTransactionsRequest(ErcotAPITest.ErcotNodalService.RequestMessage RequestMessage) {
            this.RequestMessage = RequestMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarketTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ercot.com/schema/2007-06/nodal/ews/message", Order=0)]
        public ErcotAPITest.ErcotNodalService.ResponseMessage ResponseMessage;
        
        public MarketTransactionsResponse() {
        }
        
        public MarketTransactionsResponse(ErcotAPITest.ErcotNodalService.ResponseMessage ResponseMessage) {
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationsChannel : ErcotAPITest.ErcotNodalService.Operations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationsClient : System.ServiceModel.ClientBase<ErcotAPITest.ErcotNodalService.Operations>, ErcotAPITest.ErcotNodalService.Operations {
        
        public OperationsClient() {
        }
        
        public OperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ErcotAPITest.ErcotNodalService.MarketTransactionsResponse MarketTransactions(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.MarketTransactions(request);
        }
        
        public System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> MarketTransactionsAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.MarketTransactionsAsync(request);
        }
        
        public ErcotAPITest.ErcotNodalService.MarketTransactionsResponse Alerts(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.Alerts(request);
        }
        
        public System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> AlertsAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.AlertsAsync(request);
        }
        
        public ErcotAPITest.ErcotNodalService.MarketTransactionsResponse MarketInfo(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.MarketInfo(request);
        }
        
        public System.Threading.Tasks.Task<ErcotAPITest.ErcotNodalService.MarketTransactionsResponse> MarketInfoAsync(ErcotAPITest.ErcotNodalService.MarketTransactionsRequest request) {
            return base.Channel.MarketInfoAsync(request);
        }
    }
}
